package Daje::Database::View::Super::vAuthoritiesFunctionPermissionsList;
use Mojo::Base 'Daje::Database::Model::Super::Common::Base', -base, -signatures, -async_await;
use v5.42;

# NAME
# ====
#
# Daje::Database::View::Super::vAuthoritiesFunctionPermissionsList - Daje db view
#
# SYNOPSIS
# ========
#
#
#       use Daje::Database::View::Super::vAuthoritiesFunctionPermissionsList;
#
#       my $table = Daje::Database::View::Super::vAuthoritiesFunctionPermissionsList->new(db => $db);
#
#       my $result = $table->load_authorities_function_permissions_pkey($self, $authorities_function_permissions_pkey);
#
#       my $result = $table->load_authorities_function_fkey($self, $authorities_function_fkey);
#
#       my $result = $table->load_authorities_permissions_fkey($self, $authorities_permissions_fkey);
##
#       my $result = $table->insert($self, $data);
#
#       $table->update($self, $data) ;
#
#
# DESCRIPTION
# ===========
#
# Daje::Database::View::Super::AuthoritiesFunctionPermissionsList is a Model super class
#
# METHODS
# =======
#
#
# LICENSE
# =======
#
# Copyright (C) janeskil1525.
#
# This library is free software; you can redistribute it and/or modify
# it under the same terms as Perl itself.
#
# AUTHOR
# ======
#
# janeskil1525 E<lt>janeskil1525@gmail.com
#

# This file is generated automatically by Daje Tools 2026-02-12 04:22:52.
# It will be re-created by Daje Tools again and any changes
# will be over written.
#
# <!-- Autogenerated file 2026-02-12 04:22:52 -->

our $VERSION = '0.01';

has 'fields' => '"authorities_function_permissions_pkey", "editnum", "insby", "insdatetime", "modby", "moddatetime",
"authorities_function_fkey",
"authorities_permissions_fkey"';
has 'primary_key_name' => "authorities_function_permissions_pkey";
has 'table_name' => "v_authorities_function_permissions_list";

async sub load_all_authorities_function_list_p($self) {
    return $self->load_all_authorities_function_list();
}

sub load_all_authorities_function_list($self) {
    return $self->load_a_full_list(
        $self->table_name, $self->fields()
    );
}

async sub load_authorities_function_list_p($self, $key_value) {
    return $self->load_authorities_function_list($key_value);
}

sub load_authorities_function_list($self, $key_value) {
    return $self->load_a_list(
        $self->table_name, $self->fields(), $key_value
    );
}
async sub load_all_authorities_permissions_list_p($self) {
    return $self->load_all_authorities_permissions_list();
}

sub load_all_authorities_permissions_list($self) {
    return $self->load_a_full_list(
        $self->table_name, $self->fields()
    );
}

async sub load_authorities_permissions_list_p($self, $key_value) {
    return $self->load_authorities_permissions_list($key_value);
}

sub load_authorities_permissions_list($self, $key_value) {
    return $self->load_a_list(
        $self->table_name, $self->fields(), $key_value
    );
}
async sub load_all_authorities_function_permissions_p($self) {
    return $self->load_all_authorities_function_permissions();
}

sub load_all_authorities_function_permissions($self) {
    return $self->load_a_full_list(
        $self->table_name, $self->fields()
    );
}
1;



#################### pod generated by Pod::Autopod - keep this line to make pod updates possible ####################

=head1 NAME


Daje::Database::View::Super::vAuthoritiesFunctionPermissionsList - Daje db view



=head1 SYNOPSIS



      use Daje::Database::View::Super::vAuthoritiesFunctionPermissionsList;

      my $table = Daje::Database::View::Super::vAuthoritiesFunctionPermissionsList->new(db => $db);

      my $result = $table->load_authorities_function_permissions_pkey($self, $authorities_function_permissions_pkey);

      my $result = $table->load_authorities_function_fkey($self, $authorities_function_fkey);

      my $result = $table->load_authorities_permissions_fkey($self, $authorities_permissions_fkey);

      my $result = $table->insert($self, $data);

      $table->update($self, $data) ;




=head1 DESCRIPTION


Daje::Database::View::Super::AuthoritiesFunctionPermissionsList is a Model super class



=head1 REQUIRES

L<v5.42> 

L<Mojo::Base> 


=head1 METHODS





=head1 AUTHOR


janeskil1525 E<lt>janeskil1525@gmail.com



=head1 LICENSE


Copyright (C) janeskil1525.

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.



=cut

