package Daje::Controller::Authorities::Super::AuthoritiesRoleUserList;
use Mojo::Base 'Mojolicious::Controller', -base, -signatures;
use v5.42;

# NAME
# ====
#
# Daje::Controller::Authorities::Super::AuthoritiesRoleUserList - Model class
#
# SYNOPSIS
# ========
#
#       use Daje::Controller::Authorities::Super::vAuthoritiesRoleUser##
#
# DESCRIPTION
# ===========
#
# Daje::Controller::Authorities::Super::AuthoritiesRoleUser is a standard controller
#
# METHODS
# =======
#
#
# LICENSE
# =======
#
# Copyright (C) janeskil1525.
#
# This library is free software; you can redistribute it and/or modify
# it under the same terms as Perl itself.
#
# AUTHOR
# ======
#
# janeskil1525 E<lt>janeskil1525@gmail.com
#
# This file is generated automatically by Daje Tools 2026-02-10 05:06:18.
# It will be re-generated by Daje Tools again.
# <!-- Autogenerated file 2026-02-10 05:06:18 -->

our $VERSION = '0.01';

sub load_all_authorities_role_user($self) {
    $self->app->log->debug('Daje::Controller::Super::AuthoritiesRoleUserList::load_all_authorities_role_user ');
    $self->render_later;
    my ($companies_pkey, $users_pkey) = $self->jwt->companies_users_pkey(
         $self->req->headers->header('X-Token-Check')
    );

    $self->app->log->debug($self->req->headers->header('X-Token-Check'));
    # my $setting = $self->param('setting');
    $self->v_authorities_role_user_list->load_all_authorities_role_user_p()->then(sub($result) {
        $self->render(json => $result->{data});
    })->catch(sub($err) {
        $self->app->log->error('Daje::Controller::Super::AuthoritiesRoleUserList::load_all_authorities_role_user ' . $err);
        $self->render
    });
}
sub load_list_authorities_role_fkey($self) {
    $self->app->log->debug('Daje::Controller::Super::AuthoritiesRoleUserList::load_listauthorities_role_fkey ');
    $self->render_later;
    my ($companies_pkey, $users_pkey) = $self->jwt->companies_users_pkey(
         $self->req->headers->header('X-Token-Check')
    );
    my $fkey = $self->param('authorities_role_fkey');

    $self->app->log->debug($self->req->headers->header('X-Token-Check'));
    # my $setting = $self->param('setting');
    $self->v_authorities__list->authorities_role_fkey_p($fkey)->then(sub($result) {
        $self->render(json => $result->{data});
    })->catch(sub($err) {
        $self->app->log->error('Daje::Controller::Super::AuthoritiesRoleUser::load_authorities_role_fkey ' . $err);
        $self->render
    });
}sub load_list_users_users_fkey($self) {
    $self->app->log->debug('Daje::Controller::Super::AuthoritiesRoleUserList::load_listusers_users_fkey ');
    $self->render_later;
    my ($companies_pkey, $users_pkey) = $self->jwt->companies_users_pkey(
         $self->req->headers->header('X-Token-Check')
    );
    my $fkey = $self->param('users_users_fkey');

    $self->app->log->debug($self->req->headers->header('X-Token-Check'));
    # my $setting = $self->param('setting');
    $self->v_users__list->users_users_fkey_p($fkey)->then(sub($result) {
        $self->render(json => $result->{data});
    })->catch(sub($err) {
        $self->app->log->error('Daje::Controller::Super::AuthoritiesRoleUser::load_users_users_fkey ' . $err);
        $self->render
    });
}
1;

