package Daje::Controller::Authorities::Super::AuthoritiesRole;
use Mojo::Base 'Mojolicious::Controller', -base, -signatures;
use v5.42;

# NAME
# ====
#
# Daje::Controller::Super::Authorities::AuthoritiesRole - Model class
#
# SYNOPSIS
# ========
#
#       use Daje::Controller::Authorities::Super::vAuthoritiesRole##
#
# DESCRIPTION
# ===========
#
# Daje::Controller::Authorities::Super::AuthoritiesRole is a standard controller
#
# METHODS
# =======
#
#
# LICENSE
# =======
#
# Copyright (C) janeskil1525.
#
# This library is free software; you can redistribute it and/or modify
# it under the same terms as Perl itself.
#
# AUTHOR
# ======
#
# janeskil1525 E<lt>janeskil1525@gmail.com
#
# This file is generated automatically by Daje Tools 2026-04-05 05:37:22.
# It will be re-generated by Daje Tools again.
# <!-- Autogenerated file 2026-04-05 05:37:22 -->

our $VERSION = '0.01';

sub load_authorities_role_pkey($self) {
    $self->app->log->debug('Daje::Controller::Super::AuthoritiesRole::load_authorities__fkey ');
    $self->render_later;
    my ($companies_pkey, $users_pkey) = $self->jwt->companies_users_pkey(
         $self->req->headers->header('X-Token-Check')
    );
    my $pkey = $self->param('authorities_role_pkey');

    $self->app->log->debug($self->req->headers->header('X-Token-Check'));
    # my $setting = $self->param('setting');
    $self->v_authorities_role->load_authorities_role_pkey_p($companies_pkey, $users_pkey, $pkey)->then(sub($result) {
        $self->render(json => $result->{data});
    })->catch(sub($err) {
        $self->app->log->error('Daje::Controller::Super::AuthoritiesRole::load_authorities_role_pkey ' . $err);
        $self->render
    });
}
sub load_companies_companies_fkey($self) {
    $self->app->log->debug('Daje::Controller::Super::AuthoritiesRole::load_companies_companies_fkey ');
    $self->render_later;
    my ($companies_pkey, $users_pkey) = $self->jwt->companies_users_pkey(
         $self->req->headers->header('X-Token-Check')
    );
    my $fkey = $self->param('companies_companies_fkey');

    $self->app->log->debug($self->req->headers->header('X-Token-Check'));
    # my $setting = $self->param('setting');
    $self->v_companies_->companies_companies_fkey_p($companies_pkey, $users_pkey, $fkey)->then(sub($result) {
        $self->render(json => $result->{data});
    })->catch(sub($err) {
        $self->app->log->error('Daje::Controller::Super::AuthoritiesRole::load_companies_companies_fkey ' . $err);
        $self->render
    });
}sub load_authorities_workflow_fkey($self) {
    $self->app->log->debug('Daje::Controller::Super::AuthoritiesRole::load_authorities_workflow_fkey ');
    $self->render_later;
    my ($companies_pkey, $users_pkey) = $self->jwt->companies_users_pkey(
         $self->req->headers->header('X-Token-Check')
    );
    my $fkey = $self->param('authorities_workflow_fkey');

    $self->app->log->debug($self->req->headers->header('X-Token-Check'));
    # my $setting = $self->param('setting');
    $self->v_authorities_->authorities_workflow_fkey_p($companies_pkey, $users_pkey, $fkey)->then(sub($result) {
        $self->render(json => $result->{data});
    })->catch(sub($err) {
        $self->app->log->error('Daje::Controller::Super::AuthoritiesRole::load_authorities_workflow_fkey ' . $err);
        $self->render
    });
}
1;

