package Daje::Controller::Authorities::Super::AuthoritiesFunctionPermissionsList;
use Mojo::Base 'Mojolicious::Controller', -base, -signatures;
use v5.42;

# NAME
# ====
#
# Daje::Controller::Authorities::Super::AuthoritiesFunctionPermissionsList - Model class
#
# SYNOPSIS
# ========
#
#       use Daje::Controller::Authorities::Super::vAuthoritiesFunctionPermissions##
#
# DESCRIPTION
# ===========
#
# Daje::Controller::Authorities::Super::AuthoritiesFunctionPermissions is a standard controller
#
# METHODS
# =======
#
#
# LICENSE
# =======
#
# Copyright (C) janeskil1525.
#
# This library is free software; you can redistribute it and/or modify
# it under the same terms as Perl itself.
#
# AUTHOR
# ======
#
# janeskil1525 E<lt>janeskil1525@gmail.com
#
# This file is generated automatically by Daje Tools 2026-02-12 04:22:54.
# It will be re-generated by Daje Tools again.
# <!-- Autogenerated file 2026-02-12 04:22:54 -->

our $VERSION = '0.01';

sub load_all_authorities_function_permissions($self) {
    $self->app->log->debug('Daje::Controller::Super::AuthoritiesFunctionPermissionsList::load_all_authorities_function_permissions ');
    $self->render_later;
    my ($companies_pkey, $users_pkey) = $self->jwt->companies_users_pkey(
         $self->req->headers->header('X-Token-Check')
    );

    $self->app->log->debug($self->req->headers->header('X-Token-Check'));
    # my $setting = $self->param('setting');
    $self->v_authorities_function_permissions_list->load_all_authorities_function_permissions_p()->then(sub($result) {
        $self->render(json => $result->{data});
    })->catch(sub($err) {
        $self->app->log->error('Daje::Controller::Super::AuthoritiesFunctionPermissionsList::load_all_authorities_function_permissions ' . $err);
        $self->render
    });
}
sub load_list_authorities_function_fkey($self) {
    $self->app->log->debug('Daje::Controller::Super::AuthoritiesFunctionPermissionsList::load_listauthorities_function_fkey ');
    $self->render_later;
    my ($companies_pkey, $users_pkey) = $self->jwt->companies_users_pkey(
         $self->req->headers->header('X-Token-Check')
    );
    my $fkey = $self->param('authorities_function_fkey');

    $self->app->log->debug($self->req->headers->header('X-Token-Check'));
    # my $setting = $self->param('setting');
    $self->v_authorities__list->authorities_function_fkey_p($fkey)->then(sub($result) {
        $self->render(json => $result->{data});
    })->catch(sub($err) {
        $self->app->log->error('Daje::Controller::Super::AuthoritiesFunctionPermissions::load_authorities_function_fkey ' . $err);
        $self->render
    });
}sub load_list_authorities_permissions_fkey($self) {
    $self->app->log->debug('Daje::Controller::Super::AuthoritiesFunctionPermissionsList::load_listauthorities_permissions_fkey ');
    $self->render_later;
    my ($companies_pkey, $users_pkey) = $self->jwt->companies_users_pkey(
         $self->req->headers->header('X-Token-Check')
    );
    my $fkey = $self->param('authorities_permissions_fkey');

    $self->app->log->debug($self->req->headers->header('X-Token-Check'));
    # my $setting = $self->param('setting');
    $self->v_authorities__list->authorities_permissions_fkey_p($fkey)->then(sub($result) {
        $self->render(json => $result->{data});
    })->catch(sub($err) {
        $self->app->log->error('Daje::Controller::Super::AuthoritiesFunctionPermissions::load_authorities_permissions_fkey ' . $err);
        $self->render
    });
}
1;


#################### pod generated by Pod::Autopod - keep this line to make pod updates possible ####################

=head1 NAME


Daje::Controller::Authorities::Super::AuthoritiesFunctionPermissionsList - Model class



=head1 SYNOPSIS


      use Daje::Controller::Authorities::Super::vAuthoritiesFunctionPermissions##



=head1 DESCRIPTION


Daje::Controller::Authorities::Super::AuthoritiesFunctionPermissions is a standard controller



=head1 REQUIRES

L<v5.42> 

L<Mojo::Base> 


=head1 METHODS





=head1 AUTHOR


janeskil1525 E<lt>janeskil1525@gmail.com

This file is generated automatically by Daje Tools 2026-02-12 04:22:54.
It will be re-generated by Daje Tools again.
<!-- Autogenerated file 2026-02-12 04:22:54 -->


=head1 LICENSE


Copyright (C) janeskil1525.

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.



=cut

