package Daje::Controller::Authorities::Super::AuthoritiesRoleCompanyList;
use Mojo::Base 'Mojolicious::Controller', -base, -signatures;
use v5.42;

# NAME
# ====
#
# Daje::Controller::Authorities::Super::AuthoritiesRoleCompanyList - Model class
#
# SYNOPSIS
# ========
#
#       use Daje::Controller::Authorities::Super::vAuthoritiesRoleCompany##
#
# DESCRIPTION
# ===========
#
# Daje::Controller::Authorities::Super::AuthoritiesRoleCompany is a standard controller
#
# METHODS
# =======
#
#
# LICENSE
# =======
#
# Copyright (C) janeskil1525.
#
# This library is free software; you can redistribute it and/or modify
# it under the same terms as Perl itself.
#
# AUTHOR
# ======
#
# janeskil1525 E<lt>janeskil1525@gmail.com
#
# This file is generated automatically by Daje Tools 2026-02-10 03:59:41.
# It will be re-generated by Daje Tools again.
# <!-- Autogenerated file 2026-02-10 03:59:41 -->

our $VERSION = '0.01';

sub load_all_authorities_role_company($self) {
    $self->app->log->debug('Daje::Controller::Super::AuthoritiesRoleCompanyList::load_all_authorities_role_company ');
    $self->render_later;
    my ($companies_pkey, $users_pkey) = $self->jwt->companies_users_pkey(
         $self->req->headers->header('X-Token-Check')
    );

    $self->app->log->debug($self->req->headers->header('X-Token-Check'));
    # my $setting = $self->param('setting');
    $self->v_authorities_role_company_list->load_all_authorities_role_company_p()->then(sub($result) {
        $self->render(json => $result->{data});
    })->catch(sub($err) {
        $self->app->log->error('Daje::Controller::Super::AuthoritiesRoleCompanyList::load_all_authorities_role_company ' . $err);
        $self->render
    });
}
sub load_list_authorities_role_fkey($self) {
    $self->app->log->debug('Daje::Controller::Super::AuthoritiesRoleCompanyList::load_listauthorities_role_fkey ');
    $self->render_later;
    my ($companies_pkey, $users_pkey) = $self->jwt->companies_users_pkey(
         $self->req->headers->header('X-Token-Check')
    );
    my $fkey = $self->param('authorities_role_fkey');

    $self->app->log->debug($self->req->headers->header('X-Token-Check'));
    # my $setting = $self->param('setting');
    $self->v_authorities__list->authorities_role_fkey_p($fkey)->then(sub($result) {
        $self->render(json => $result->{data});
    })->catch(sub($err) {
        $self->app->log->error('Daje::Controller::Super::AuthoritiesRoleCompany::load_authorities_role_fkey ' . $err);
        $self->render
    });
}sub load_list_companies_companies_fkey($self) {
    $self->app->log->debug('Daje::Controller::Super::AuthoritiesRoleCompanyList::load_listcompanies_companies_fkey ');
    $self->render_later;
    my ($companies_pkey, $users_pkey) = $self->jwt->companies_users_pkey(
         $self->req->headers->header('X-Token-Check')
    );
    my $fkey = $self->param('companies_companies_fkey');

    $self->app->log->debug($self->req->headers->header('X-Token-Check'));
    # my $setting = $self->param('setting');
    $self->v_companies__list->companies_companies_fkey_p($fkey)->then(sub($result) {
        $self->render(json => $result->{data});
    })->catch(sub($err) {
        $self->app->log->error('Daje::Controller::Super::AuthoritiesRoleCompany::load_companies_companies_fkey ' . $err);
        $self->render
    });
}
1;

