package Daje::Database::Authorities;
use Mojo::Base -base;
use v5.42;

our $VERSION = '1';

1;

__DATA__

@@ authorities

-- 1 up

-- Autogenerated file, any changes to this file will be over written.
-- Last generated 2026-02-09 17:53:23

    
CREATE TABLE IF NOT EXISTS authorities_role_user
(
    authorities_role_user_pkey  SERIAL NOT NULL,
    editnum bigint NOT NULL DEFAULT 1,
    insby character varying COLLATE pg_catalog."default" NOT NULL DEFAULT 'System'::character varying,
    insdatetime timestamp without time zone NOT NULL DEFAULT now(),
    modby character varying COLLATE pg_catalog."default" NOT NULL DEFAULT 'System'::character varying,
    moddatetime timestamp without time zone NOT NULL DEFAULT now(),
            authorities_role_fkey BIGINT  NOT NULL,
                    users_users_fkey BIGINT  NOT NULL,
                CONSTRAINT authorities_role_user_pkey PRIMARY KEY (authorities_role_user_pkey)
);
    
CREATE TABLE IF NOT EXISTS authorities_role_company
(
    authorities_role_company_pkey  SERIAL NOT NULL,
    editnum bigint NOT NULL DEFAULT 1,
    insby character varying COLLATE pg_catalog."default" NOT NULL DEFAULT 'System'::character varying,
    insdatetime timestamp without time zone NOT NULL DEFAULT now(),
    modby character varying COLLATE pg_catalog."default" NOT NULL DEFAULT 'System'::character varying,
    moddatetime timestamp without time zone NOT NULL DEFAULT now(),
            authorities_role_fkey BIGINT  NOT NULL,
                    companies_companies_fkey BIGINT  NOT NULL,
                CONSTRAINT authorities_role_company_pkey PRIMARY KEY (authorities_role_company_pkey)
);
    
CREATE TABLE IF NOT EXISTS authorities_role
(
    authorities_role_pkey  SERIAL NOT NULL,
    editnum bigint NOT NULL DEFAULT 1,
    insby character varying COLLATE pg_catalog."default" NOT NULL DEFAULT 'System'::character varying,
    insdatetime timestamp without time zone NOT NULL DEFAULT now(),
    modby character varying COLLATE pg_catalog."default" NOT NULL DEFAULT 'System'::character varying,
    moddatetime timestamp without time zone NOT NULL DEFAULT now(),
            authorities_function_fkey BIGINT  NOT NULL,
                    companies_companies_fkey BIGINT  NOT NULL,
                        name  VARCHAR  NOT NULL ,
                CONSTRAINT authorities_role_pkey PRIMARY KEY (authorities_role_pkey)
);
    
CREATE TABLE IF NOT EXISTS authorities_plugin
(
    authorities_plugin_pkey  SERIAL NOT NULL,
    editnum bigint NOT NULL DEFAULT 1,
    insby character varying COLLATE pg_catalog."default" NOT NULL DEFAULT 'System'::character varying,
    insdatetime timestamp without time zone NOT NULL DEFAULT now(),
    modby character varying COLLATE pg_catalog."default" NOT NULL DEFAULT 'System'::character varying,
    moddatetime timestamp without time zone NOT NULL DEFAULT now(),
                name  VARCHAR  UNIQUE  NOT NULL ,
                CONSTRAINT authorities_plugin_pkey PRIMARY KEY (authorities_plugin_pkey)
);
    
CREATE TABLE IF NOT EXISTS authorities_function
(
    authorities_function_pkey  SERIAL NOT NULL,
    editnum bigint NOT NULL DEFAULT 1,
    insby character varying COLLATE pg_catalog."default" NOT NULL DEFAULT 'System'::character varying,
    insdatetime timestamp without time zone NOT NULL DEFAULT now(),
    modby character varying COLLATE pg_catalog."default" NOT NULL DEFAULT 'System'::character varying,
    moddatetime timestamp without time zone NOT NULL DEFAULT now(),
            authorities_plugin_fkey BIGINT  NOT NULL,
                        name  VARCHAR  UNIQUE  NOT NULL ,
                CONSTRAINT authorities_function_pkey PRIMARY KEY (authorities_function_pkey)
);
    
CREATE TABLE IF NOT EXISTS authorities_permissions
(
    authorities_permissions_pkey  SERIAL NOT NULL,
    editnum bigint NOT NULL DEFAULT 1,
    insby character varying COLLATE pg_catalog."default" NOT NULL DEFAULT 'System'::character varying,
    insdatetime timestamp without time zone NOT NULL DEFAULT now(),
    modby character varying COLLATE pg_catalog."default" NOT NULL DEFAULT 'System'::character varying,
    moddatetime timestamp without time zone NOT NULL DEFAULT now(),
                permission  VARCHAR  UNIQUE  NOT NULL ,
                        standard  BOOLEAN  NOT NULL DEFAULT true ,
                CONSTRAINT authorities_permissions_pkey PRIMARY KEY (authorities_permissions_pkey)
);
    
CREATE TABLE IF NOT EXISTS authorities_function_permissions
(
    authorities_function_permissions_pkey  SERIAL NOT NULL,
    editnum bigint NOT NULL DEFAULT 1,
    insby character varying COLLATE pg_catalog."default" NOT NULL DEFAULT 'System'::character varying,
    insdatetime timestamp without time zone NOT NULL DEFAULT now(),
    modby character varying COLLATE pg_catalog."default" NOT NULL DEFAULT 'System'::character varying,
    moddatetime timestamp without time zone NOT NULL DEFAULT now(),
            authorities_function_fkey BIGINT  NOT NULL,
                    authorities_permissions_fkey BIGINT  NOT NULL,
                CONSTRAINT authorities_function_permissions_pkey PRIMARY KEY (authorities_function_permissions_pkey)
);
    
CREATE TABLE IF NOT EXISTS authorities_license_plugin
(
    authorities_license_plugin_pkey  SERIAL NOT NULL,
    editnum bigint NOT NULL DEFAULT 1,
    insby character varying COLLATE pg_catalog."default" NOT NULL DEFAULT 'System'::character varying,
    insdatetime timestamp without time zone NOT NULL DEFAULT now(),
    modby character varying COLLATE pg_catalog."default" NOT NULL DEFAULT 'System'::character varying,
    moddatetime timestamp without time zone NOT NULL DEFAULT now(),
            authorities_plugin_fkey BIGINT  NOT NULL,
                        licensed  BOOLEAN  NOT NULL DEFAULT false ,
                    companies_companies_fkey BIGINT  NOT NULL,
                CONSTRAINT authorities_license_plugin_pkey PRIMARY KEY (authorities_license_plugin_pkey)
);
    
CREATE TABLE IF NOT EXISTS authorities_license_function
(
    authorities_license_function_pkey  SERIAL NOT NULL,
    editnum bigint NOT NULL DEFAULT 1,
    insby character varying COLLATE pg_catalog."default" NOT NULL DEFAULT 'System'::character varying,
    insdatetime timestamp without time zone NOT NULL DEFAULT now(),
    modby character varying COLLATE pg_catalog."default" NOT NULL DEFAULT 'System'::character varying,
    moddatetime timestamp without time zone NOT NULL DEFAULT now(),
            authorities_function_fkey BIGINT  NOT NULL,
                    companies_companies_fkey BIGINT  NOT NULL,
                        licensed  BOOLEAN  NOT NULL DEFAULT false ,
                CONSTRAINT authorities_license_function_pkey PRIMARY KEY (authorities_license_function_pkey)
);
    

CREATE OR REPLACE VIEW v_authorities_role_user AS
    SELECT authorities_role_user_pkey, editnum, insby, insdatetime, modby, moddatetime,authorities_role_fkey,
     users_users_fkey
          FROM authorities_role_user;
CREATE OR REPLACE VIEW v_authorities_role_company AS
    SELECT authorities_role_company_pkey, editnum, insby, insdatetime, modby, moddatetime,authorities_role_fkey,
     companies_companies_fkey
          FROM authorities_role_company;
CREATE OR REPLACE VIEW v_authorities_role AS
    SELECT authorities_role_pkey, editnum, insby, insdatetime, modby, moddatetime,authorities_function_fkey,
     companies_companies_fkey,
      name
          FROM authorities_role;
CREATE OR REPLACE VIEW v_authorities_plugin AS
    SELECT authorities_plugin_pkey, editnum, insby, insdatetime, modby, moddatetime, name
          FROM authorities_plugin;
CREATE OR REPLACE VIEW v_authorities_function AS
    SELECT authorities_function_pkey, editnum, insby, insdatetime, modby, moddatetime,authorities_plugin_fkey,
      name
          FROM authorities_function;
CREATE OR REPLACE VIEW v_authorities_permissions AS
    SELECT authorities_permissions_pkey, editnum, insby, insdatetime, modby, moddatetime, permission,
      standard
          FROM authorities_permissions;
CREATE OR REPLACE VIEW v_authorities_function_permissions AS
    SELECT authorities_function_permissions_pkey, editnum, insby, insdatetime, modby, moddatetime,authorities_function_fkey,
     authorities_permissions_fkey
          FROM authorities_function_permissions;
CREATE OR REPLACE VIEW v_authorities_license_plugin AS
    SELECT authorities_license_plugin_pkey, editnum, insby, insdatetime, modby, moddatetime,authorities_plugin_fkey,
      licensed,
     companies_companies_fkey
          FROM authorities_license_plugin;
CREATE OR REPLACE VIEW v_authorities_license_function AS
    SELECT authorities_license_function_pkey, editnum, insby, insdatetime, modby, moddatetime,authorities_function_fkey,
     companies_companies_fkey,
      licensed
          FROM authorities_license_function;


CREATE OR REPLACE VIEW v_authorities_role_user_list AS
    SELECT authorities_role_user_pkey, editnum, insby, insdatetime, modby, moddatetime,     (SELECT name FROM authorities_role WHERE authorities_role_pkey = authorities_role_fkey) as authorities_role_name,authorities_role_fkey,      (SELECT name FROM users_users WHERE users_users_pkey = users_users_fkey) as users_users_name,users_users_fkey     FROM authorities_role_user;

CREATE OR REPLACE VIEW v_authorities_role_company_list AS
    SELECT authorities_role_company_pkey, editnum, insby, insdatetime, modby, moddatetime,authorities_role_fkey,companies_companies_fkey     FROM authorities_role_company;

CREATE OR REPLACE VIEW v_authorities_role_list AS
    SELECT authorities_role_pkey, editnum, insby, insdatetime, modby, moddatetime,     (SELECT name FROM authorities_function WHERE authorities_function_pkey = authorities_function_fkey) as authorities_function_name,authorities_function_fkey,companies_companies_fkey, name     FROM authorities_role;

CREATE OR REPLACE VIEW v_authorities_plugin_list AS
    SELECT authorities_plugin_pkey, editnum, insby, insdatetime, modby, moddatetime, name     FROM authorities_plugin;

CREATE OR REPLACE VIEW v_authorities_function_list AS
    SELECT authorities_function_pkey, editnum, insby, insdatetime, modby, moddatetime,authorities_plugin_fkey, name     FROM authorities_function;

CREATE OR REPLACE VIEW v_authorities_permissions_list AS
    SELECT authorities_permissions_pkey, editnum, insby, insdatetime, modby, moddatetime, permission, standard     FROM authorities_permissions;

CREATE OR REPLACE VIEW v_authorities_function_permissions_list AS
    SELECT authorities_function_permissions_pkey, editnum, insby, insdatetime, modby, moddatetime,authorities_function_fkey,authorities_permissions_fkey     FROM authorities_function_permissions;

CREATE OR REPLACE VIEW v_authorities_license_plugin_list AS
    SELECT authorities_license_plugin_pkey, editnum, insby, insdatetime, modby, moddatetime,authorities_plugin_fkey, licensed,companies_companies_fkey     FROM authorities_license_plugin;

CREATE OR REPLACE VIEW v_authorities_license_function_list AS
    SELECT authorities_license_function_pkey, editnum, insby, insdatetime, modby, moddatetime,authorities_function_fkey,companies_companies_fkey, licensed     FROM authorities_license_function;




ALTER TABLE authorities_role_user
    ADD CONSTRAINT authorities_role_user_authorities_role_fkey
FOREIGN KEY (authorities_role_fkey)
    REFERENCES authorities_role (authorities_role_pkey);


CREATE INDEX ind_authorities_role_user_role_fkey
    ON authorities_role_user(authorities_role_fkey);

  ALTER TABLE authorities_role_user
    ADD CONSTRAINT users_role_user_users_users_fkey
FOREIGN KEY (users_users_fkey)

    REFERENCES users_users (users_users_pkey);


CREATE INDEX ind_users_role_user_users_fkey
    ON authorities_role_user(users_users_fkey);

  
    ALTER TABLE authorities_role_company
    ADD CONSTRAINT authorities_role_company_authorities_role_fkey
FOREIGN KEY (authorities_role_fkey)
    REFERENCES authorities_role (authorities_role_pkey);


CREATE INDEX ind_authorities_role_company_role_fkey
    ON authorities_role_company(authorities_role_fkey);

  ALTER TABLE authorities_role_company
    ADD CONSTRAINT companies_role_company_companies_companies_fkey
FOREIGN KEY (companies_companies_fkey)

    REFERENCES companies_companies (companies_companies_pkey);


CREATE INDEX ind_companies_role_company_companies_fkey
    ON authorities_role_company(companies_companies_fkey);

  
    ALTER TABLE authorities_role
    ADD CONSTRAINT authorities_role_authorities_function_fkey
FOREIGN KEY (authorities_function_fkey)
    REFERENCES authorities_function (authorities_function_pkey);


CREATE INDEX ind_authorities_role_function_fkey
    ON authorities_role(authorities_function_fkey);

  ALTER TABLE authorities_role
    ADD CONSTRAINT companies_role_companies_companies_fkey
FOREIGN KEY (companies_companies_fkey)

    REFERENCES companies_companies (companies_companies_pkey);


CREATE INDEX ind_companies_role_companies_fkey
    ON authorities_role(companies_companies_fkey);

  
  
    
    ALTER TABLE authorities_function
    ADD CONSTRAINT authorities_function_authorities_plugin_fkey
FOREIGN KEY (authorities_plugin_fkey)
    REFERENCES authorities_plugin (authorities_plugin_pkey);


CREATE INDEX ind_authorities_function_plugin_fkey
    ON authorities_function(authorities_plugin_fkey);

  
    
  
    ALTER TABLE authorities_function_permissions
    ADD CONSTRAINT authorities_function_permissions_authorities_function_fkey
FOREIGN KEY (authorities_function_fkey)
    REFERENCES authorities_function (authorities_function_pkey);


CREATE INDEX ind_authorities_function_permissions_function_fkey
    ON authorities_function_permissions(authorities_function_fkey);

  ALTER TABLE authorities_function_permissions
    ADD CONSTRAINT authorities_function_permissions_authorities_permissions_fkey
FOREIGN KEY (authorities_permissions_fkey)
    REFERENCES authorities_permissions (authorities_permissions_pkey);


CREATE INDEX ind_authorities_function_permissions_permissions_fkey
    ON authorities_function_permissions(authorities_permissions_fkey);

    ALTER TABLE authorities_license_plugin
    ADD CONSTRAINT authorities_license_plugin_authorities_plugin_fkey
FOREIGN KEY (authorities_plugin_fkey)
    REFERENCES authorities_plugin (authorities_plugin_pkey);


CREATE INDEX ind_authorities_license_plugin_plugin_fkey
    ON authorities_license_plugin(authorities_plugin_fkey);

  
  ALTER TABLE authorities_license_plugin
    ADD CONSTRAINT companies_license_plugin_companies_companies_fkey
FOREIGN KEY (companies_companies_fkey)

    REFERENCES companies_companies (companies_companies_pkey);


CREATE INDEX ind_companies_license_plugin_companies_fkey
    ON authorities_license_plugin(companies_companies_fkey);

  
    ALTER TABLE authorities_license_function
    ADD CONSTRAINT authorities_license_function_authorities_function_fkey
FOREIGN KEY (authorities_function_fkey)
    REFERENCES authorities_function (authorities_function_pkey);


CREATE INDEX ind_authorities_license_function_function_fkey
    ON authorities_license_function(authorities_function_fkey);

  ALTER TABLE authorities_license_function
    ADD CONSTRAINT companies_license_function_companies_companies_fkey
FOREIGN KEY (companies_companies_fkey)

    REFERENCES companies_companies (companies_companies_pkey);


CREATE INDEX ind_companies_license_function_companies_fkey
    ON authorities_license_function(companies_companies_fkey);

  
  
    
-- 1 down



@@ the_end


