package Daje::Database::View::vAuthoritiesRoleUser;
use Mojo::Base 'Daje::Database::View::Super::vAuthoritiesRoleUser', -base, -async_await, -signatures;
use v5.42;

# NAME
# ====
#
# Daje::Database::View::vAuthoritiesRoleUser - View class
#
# SYNOPSIS
# ========
#
#       use Daje::Database::View::vAuthoritiesRoleUser;
#
#       my $class = Daje::Database::View::vAuthoritiesRoleUser->new(db => $db);
#
# DESCRIPTION
# ===========
#
# Daje::Database::View::vAuthoritiesRoleUser is the View
#
# class that's only generated once. It inherits all
#
# methods from Daje::Database::View::Super::vAuthoritiesRoleUser#
# This class is meant for non standard methods.
#
# METHODS
# =======
#
#
# LICENSE
# =======
#
# Copyright (C) janeskil1525.
#
# This library is free software; you can redistribute it and/or modify
# it under the same terms as Perl itself.
#
# AUTHOR
# ======
#
# janeskil1525 E<lt>janeskil1525@gmail.com
#

# This file is generated once automatically by Daje Tools 2026-02-09 17:53:25.
# It will not be touched by Daje Tools again.
# <!-- Autogenerated file 2026-02-09 17:53:25 -->


our $VERSION = '0.01';

1;

