package Daje::Plugin::Authorities::Authorities;
use Mojo::Base -base, -signatures;
use v5.42;

# NAME
# ====
#
# Daje::Plugin::Authorities::Authorities - Model class
#
# SYNOPSIS
# ========
#
#
#
#
# DESCRIPTION
# ===========
#
# Daje::Plugin::Authorities::Authorities is the standard routes
#
# METHODS
# =======
#
#
# LICENSE
# =======
#
# Copyright (C) janeskil1525.
#
# This library is free software; you can redistribute it and/or modify
# it under the same terms as Perl itself.
#
# AUTHOR
# ======
#
# janeskil1525 E<lt>janeskil1525@gmail.com
#

# This file is generated automatically by Daje Tools 2026-02-10 05:06:18.
# It will be generated by Daje Tools again.
# <!-- Autogenerated file 2026-02-10 05:06:18 -->

use Daje::Helper::Authorities::InsertPluginFunction;

sub authorize($self, $app) {

    my @functions = (
        "authorities_role_user",
        "authorities_role",
        "authorities_role_function",
        "authorities_license",
        "authorities_plugin",
        "authorities_function",
        "authorities_permissions",
        "authorities_function_permissions",
        "authorities_license_plugin",
        "authorities_license_function",
        "authorities_license_companies"
    );

    Daje::Helper::Authorities::InsertPluginFunction->new(
        )->process($app, "authorities", \@functions);

}

1;

