package Daje::Controller::Authorities::AuthoritiesRoleCompany;
use Mojo::Base 'Daje::Controller::Authorities::Super::AuthoritiesRoleCompany', -base, -signatures;
use v5.42;

# NAME
# ====
#
# Daje::Controller::Authorities::AuthoritiesRoleCompany - Controller class
#
# SYNOPSIS
# ========
#
#       use Daje::Controller::Authorities::AuthoritiesRoleCompany
#
#
#
# DESCRIPTION
# ===========
#
# Daje::Controller::Authorities::AuthoritiesRoleCompany is a standard controller
#
# METHODS
# =======
#
#
# LICENSE
# =======
#
# Copyright (C) janeskil1525.
#
# This library is free software; you can redistribute it and/or modify
# it under the same terms as Perl itself.
#
# AUTHOR
# ======
#
# janeskil1525 E<lt>janeskil1525@gmail.com
#

# This file is generated automatically by Daje Tools 2026-02-10 03:59:41.
# It will not be re-generated by Daje Tools again.
# <!-- Autogenerated file 2026-02-10 03:59:41 -->

our $VERSION = '0.01';

1;

