package Daje::Controller::Authorities::AuthoritiesRole;
use Mojo::Base 'Daje::Controller::Authorities::Super::AuthoritiesRole', -base, -signatures;
use v5.42;

# NAME
# ====
#
# Daje::Controller::Authorities::AuthoritiesRole - Controller class
#
# SYNOPSIS
# ========
#
#       use Daje::Controller::Authorities::AuthoritiesRole
#
#
#
# DESCRIPTION
# ===========
#
# Daje::Controller::Authorities::AuthoritiesRole is a standard controller
#
# METHODS
# =======
#
#
# LICENSE
# =======
#
# Copyright (C) janeskil1525.
#
# This library is free software; you can redistribute it and/or modify
# it under the same terms as Perl itself.
#
# AUTHOR
# ======
#
# janeskil1525 E<lt>janeskil1525@gmail.com
#

# This file is generated automatically by Daje Tools 2026-02-12 17:06:04.
# It will not be re-generated by Daje Tools again.
# <!-- Autogenerated file 2026-02-12 17:06:04 -->

our $VERSION = '0.01';

sub load_authorities_role_full($self) {
    $self->app->log->debug('Daje::Controller::Super::AuthoritiesRole::load_authorities__fkey ');
    $self->render_later;
    my ($companies_pkey, $users_pkey) = $self->jwt->companies_users_pkey(
        $self->req->headers->header('X-Token-Check')
    );

    $self->app->log->debug($self->req->headers->header('X-Token-Check'));
    # my $setting = $self->param('setting');
    $self->helper_authorities->load_authorities_role_pkey_p($companies_pkey, $users_pkey, $pkey)->then(sub($result) {
        $self->render(text => $result->{data});
    })->catch(sub($err) {
        $self->app->log->error('Daje::Controller::AuthoritiesRole::load_authorities_role_pkey ' . $err);
        $self->render
    });
}

1;

